name: Build with the JDK 8

on:
  push:
    branches:
      - master
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - master
  schedule:
    - cron: '15 11 1 */1 *' # once a month on the first day

env:
  JDKVERSION: 8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-${{ env.JDKVERSION }}
          key: ${{ runner.os }}-${{ env.JDKVERSION }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.JDKVERSION }}-buildx-

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "./Dockerfile"
          build-args: |
            JDKVERSION=${{ env.JDKVERSION }}
          tags: ${{ github.repository }}:${{ github.sha }}-${{ env.JDKVERSION }}
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache-${{ env.JDKVERSION }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ env.JDKVERSION }}-new

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.repository }}:${{ github.sha }}-${{ env.JDKVERSION }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          timeout: '30m'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-${{ env.JDKVERSION }}
          mv /tmp/.buildx-cache-${{ env.JDKVERSION }}-new /tmp/.buildx-cache-${{ env.JDKVERSION }}
