name: Release with the JDK 8

on:
  push:
    tags:
      - "v*"

env:
  GHCR_IMAGE: ghcr.io/${{ github.repository }}
  JDKVERSION: 8

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-${{ env.JDKVERSION }}
          key: ${{ runner.os }}-${{ env.JDKVERSION }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.JDKVERSION }}-buildx-

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.GHCR_IMAGE }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}},suffix=.jdk${{ env.JDKVERSION }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        if: ${{ env.GHCR_IMAGE }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "./Dockerfile"
          build-args: |
            JDKVERSION=${{ env.JDKVERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache-${{ env.JDKVERSION }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ env.JDKVERSION }}-new
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-${{ env.JDKVERSION }}
          mv /tmp/.buildx-cache-${{ env.JDKVERSION }}-new /tmp/.buildx-cache-${{ env.JDKVERSION }}
